[FEATURE] Router
ThomasStinkensPXL/FrontendOnboardingThomasStinkens pull request #3
Opened 2024-02-27 15:21 UTC by ThomasStinkensPXL

Added a new router that redirect the users to the correct page (login, todos or 404error). Also made sure a user it authenticated when necessary (beforeEach in the router).

The way I check if a user is authenticated is by always getting the user info after a succesful login, this garuantees that currentUser is no longer null after a login.

2024-02-27 16:24 UTC, maltsavkiryl requested changes

2024-02-27 16:24 UTC, maltsavkiryl commented on src/modules/auth/views/AuthLoginView.vue
> +export default {
deze export default is niet nodig :)

2024-02-27 16:24 UTC, maltsavkiryl commented on src/views/Error404View.vue
> +	name: 'Error404View',
export default is niet nodig :)

2024-02-27 16:24 UTC, maltsavkiryl commented on src/views/TodoOverviewView.vue
> +export default {
hier mag ie ook weg :)

2024-02-27 20:13 UTC, JeroenVanC commented on src/modules/auth/views/AuthLoginView.vue
> +export default {
<script setup> van maken

2024-02-27 20:14 UTC, JeroenVanC requested changes

2024-02-27 20:14 UTC, JeroenVanC commented on src/modules/auth/views/AuthLoginView.vue
> +<style scoped>
style mag ook weg !

2024-02-27 20:14 UTC, JeroenVanC commented on src/modules/auth/views/AuthLoginView.vue
> +<style scoped>
altijd tailwind gebruiken

2024-02-28 13:22 UTC, maltsavkiryl approved these changes

2024-02-28 15:22 UTC, merged