[FEATURE] Login view
ThomasStinkensPXL/FrontendOnboardingThomasStinkens pull request #4
Opened 2024-02-28 15:27 UTC by ThomasStinkensPXL

UI for user login.

2024-02-28 21:00 UTC, JeroenVanC requested changes
Ziet er heel goed uit ! paar kleine opmerkingen/tips. Ge moogt ook altijd die opmerking aanpassen indeze branch, mij sturen en dan aprove ik. anders zie ik al uw aanpassingen in het volgend PR en das niet echt nodig :)

2024-02-28 21:00 UTC, JeroenVanC commented on src/modules/auth/components/AuthLoginForm.vue
> +			<label
Ik zou label + input samen in 1 component steken genaamd FormLabel zo kunt ge da easy overal hergebruiken, want da is toch overal hetzelfde

2024-02-28 21:00 UTC, JeroenVanC commented on src/modules/auth/components/AuthLoginForm.vue
> +		<button
AppButton.vue component maken, zo hoeft ge maar 1 keer uw styling te doen. ge kunt ook varianten toevoegen als dat nodig zou zijn

2024-02-28 21:00 UTC, JeroenVanC commented on src/router/index.ts
> -import { createRouter, createWebHistory } from 'vue-router'
deze file mag weg

2024-02-28 21:00 UTC, JeroenVanC commented on src/router/router.ts
> +		name: 'login',
ge kunt van al uw names een enum maken. zo kunt gw overal in uw code 100% zeker dezelfde altijd gebruiken.

2024-02-28 21:00 UTC, JeroenVanC commented on src/views/TodoOverviewView.vue
> +	<p>Overview!</p>
ook vertalen ;)

2024-02-28 21:00 UTC, JeroenVanC commented on src/views/Error404View.vue
> +	<h1>404 Not Found</h1>
i18n !

2024-02-28 21:00 UTC, JeroenVanC commented on src/modules/auth/stores/auth.store.ts
> +		await getCurrentUser()
waarom hebt ge dit toegevoegd?

2024-02-29 08:47 UTC, maltsavkiryl requested changes
Nog een paar dingen je moet aanpassen, maar ziet er al heel goed uit 👌

2024-02-29 08:47 UTC, maltsavkiryl commented on src/modules/auth/components/AuthLoginForm.vue
> +const password = ref<string>('')
Formango gebruiken voor form validation ;)

2024-02-29 08:47 UTC, maltsavkiryl commented on src/modules/auth/components/AuthLoginForm.vue
> +			<input
je gaat dan ook custom inputs moeten maken om formango te binden op uw inputs

2024-02-29 08:47 UTC, maltsavkiryl commented on src/modules/auth/views/AuthLoginView.vue
> +			<h1 class="w-[360px] text-3xl font-semibold">{{ t('auth.login.welcome') }}</h1>
van deze kan je ook components maken, bv `AppTitle` en `AppText`. Dan kan je al die styling daar in wegsteken

2024-02-29 12:01 UTC, ThomasStinkensPXL commented on src/router/index.ts
> -import { createRouter, createWebHistory } from 'vue-router'
Can I blame git? (Staat al niet meer in mijn local repo)

2024-02-29 12:05 UTC, ThomasStinkensPXL commented on src/router/router.ts
> +		name: 'login',
Enkel van de routeNames of ook de paths?

2024-02-29 13:37 UTC, JeroenVanC commented on src/router/router.ts
> +		name: 'login',
route names!

2024-02-29 13:40 UTC, ThomasStinkensPXL commented on src/modules/auth/stores/auth.store.ts
> +		await getCurrentUser()
Het nakijken of iemand is ingelogd gebeurt op dit moment door na te kijken of er een currentUser is. Een alternatief zou zijn door te kijken of de accesstoken aanwezig is.

2024-02-29 14:51 UTC, JeroenVanC approved these changes

2024-02-29 18:21 UTC, maltsavkiryl approved these changes

2024-03-01 14:49 UTC, merged